// Shared per-feed presentation: stroke color and legend value formatter.
// Single source of truth for ChartContainer (stroke colors) and PaneStack
// (legend pills, stat tiles).

export const FEED_COLOR: Record<string, string> = {
  da_lmp: "#4f8cff",
  rt_lmp: "#f97362",
  reg_rmccp: "#a78bfa",
  reg_rmpcp: "#34d399",
  da_sr_mcp: "#22d3ee",
  rt_sr_mcp: "#fb7185",
  reg_requirement: "#94a3b8",
  reg_perfscore: "#facc15",
  load_metered: "#f97316",
  solar_gen: "#fde047",
  wind_gen: "#38bdf8",
  da_rt_spread_pos: "#34d399",
  da_rt_spread_neg: "#fb7185",
  net_load_pos: "#34d399",
  net_load_neg: "#fb7185",
  gen_outage_total: "#94a3b8",
  gen_outage_forced: "#fb7185",
  gen_outage_planned: "#a78bfa",
  gen_outage_maintenance: "#facc15",
  rto_load_actual: "#94a3b8",
  rto_load_forecast_da: "#4f8cff",
  rto_load_forecast_1h: "#fbbf24",
  rto_load_forecast_asof: "#34d399",
  rto_solar_actual: "#fde047",
  rto_solar_forecast_da: "#4f8cff",
  rto_solar_forecast_1h: "#fbbf24",
  rto_solar_forecast_asof: "#34d399",
  rto_wind_actual: "#38bdf8",
  rto_wind_forecast_da: "#a78bfa",
  rto_wind_forecast_1h: "#f97362",
  rto_wind_forecast_asof: "#22d3ee",
  rto_net_load_actual: "#94a3b8",
  rto_net_load_forecast_da: "#4f8cff",
  rto_net_load_forecast_1h: "#fbbf24",
  rto_net_load_forecast_asof: "#34d399",
  // Strategy overlay (violet = "this strategy", gold = PF oracle).
  strategy_cleared_pos: "#a78bfa",
  strategy_cleared_neg: "#fb7185",
  strategy_cum_revenue: "#a78bfa",
  strategy_pf_ceiling: "#fbbf24",
};

export const FEED_FORMAT: Record<string, (v: number) => string> = {
  da_lmp: (v) => `$${v.toFixed(2)}`,
  rt_lmp: (v) => `$${v.toFixed(2)}`,
  reg_rmccp: (v) => `$${v.toFixed(2)}`,
  reg_rmpcp: (v) => `$${v.toFixed(2)}`,
  da_sr_mcp: (v) => `$${v.toFixed(2)}`,
  rt_sr_mcp: (v) => `$${v.toFixed(2)}`,
  reg_requirement: (v) => `${v.toFixed(0)} MW`,
  reg_perfscore: (v) => v.toFixed(3),
  load_metered: (v) => `${v.toFixed(0)} MW`,
  solar_gen: (v) => `${v.toFixed(0)} MW`,
  wind_gen: (v) => `${v.toFixed(0)} MW`,
  da_rt_spread_pos: (v) => `+$${v.toFixed(2)}`,
  da_rt_spread_neg: (v) => `−$${Math.abs(v).toFixed(2)}`,
  net_load_pos: (v) => `+${v.toFixed(0)} MW`,
  net_load_neg: (v) => `${v.toFixed(0)} MW`,
  gen_outage_total: (v) => `${(v / 1000).toFixed(1)} GW`,
  gen_outage_forced: (v) => `${(v / 1000).toFixed(1)} GW`,
  gen_outage_planned: (v) => `${(v / 1000).toFixed(1)} GW`,
  gen_outage_maintenance: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_load_actual: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_load_forecast_da: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_load_forecast_1h: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_load_forecast_asof: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_solar_actual: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_solar_forecast_da: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_solar_forecast_1h: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_solar_forecast_asof: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_wind_actual: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_wind_forecast_da: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_wind_forecast_1h: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_wind_forecast_asof: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_net_load_actual: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_net_load_forecast_da: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_net_load_forecast_1h: (v) => `${(v / 1000).toFixed(1)} GW`,
  rto_net_load_forecast_asof: (v) => `${(v / 1000).toFixed(1)} GW`,
  strategy_cleared_pos: (v) => `+${v.toFixed(1)} MW`,
  strategy_cleared_neg: (v) => `${v.toFixed(1)} MW`,
  strategy_cum_revenue: (v) => `$${(v / 1000).toFixed(1)}k`,
  strategy_pf_ceiling: (v) => `$${(v / 1000).toFixed(1)}k`,
};
